### PR TITLE
added tkHighPT muon ID

### PR DESCRIPTION
**Pull request by skeshri**
Hi All,

I have added tkHighPT ID for Muon.
Please take a look. 

Thanks,
Sumit

### CODE REVIEW

**Comment by georgia14** [comment]
Hi @skeshri 
Can you add the application of the high-pt muon id in main analysis code, so that we use it be default for Moriond 17?
Thanks

**Comment by skeshri** [comment]
Hi @georgia14
Yes I can. But I have one question. As far as I understand this ID is meant only for High PT muons. So would I apply this ID with some PT cut (let say after 200 GeV or so) ? Or should I do "OR" of this tkHighPT ID with tight muon ID?
Thanks

**Comment by georgia14** [comment]
I think in our case, where we apply a rather low Zpt cut (55 GeV ) , we will need to OR this tkHighPt id with the standard tightMuonId . @HuguesBrun may comment further .
cheers, Georgia

**Comment by HuguesBrun** [comment]
Hi @skeshri and @georgia14, 
I don't think that OR would change things because this tkHighPt is looser than the tight ID 
The problem is in term of the control of the fakes: it is possible that in the low pT muon region, the tkHighPt will have a lager fake rate than the tightID... From the selection, I would think that is still tight so I would not expect the fakes to explode. This said, I did not see any studies from the B2G group regarding that. 
What I would do it to rerun our analysis with this tkHighPt and make sure that we see an negligible increase of the DATA and background yields

**Comment by georgia14** [comment]
Hi @skeshri , @HuguesBrun 
So 4lep and 2l2q apply the high-pT muon id practically for Zpt > 200 . Here is how it is used in their case (and we should do the same ) : https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsZZ4l2016#Muons

**Comment by HuguesBrun** [comment]
For pT > 200 you mean 
Also they are not exactly in the same use case as their ID is in fact looser for muon with pT <200 GeV o they want to preserve a high efficiency at low pT (they do not care of fakes: they have 4 muons ! ) 
I think that our use case is slightly different

**Pull request merged**
