### PR TITLE
New Changes for 76X

### PR DESCRIPTION
**Pull request by amagitte**
Hi all,

The main changes are:
1- TAGS.txt (adapted to be used in 76X)
2- bin/hzz2l2v/runHZZ2l2vAnalysis.cc -> fixed the Electron and Photon energy scale with the new function
3- test/hzz2l2v/samples.json -> added new samples (same samples are lacking)
4- New Golden Jeson
5- bin/BuildFile.xml -> I have commented out a file because it doesn't compile (is one of the other analysis)
6- test/hzz2l2v/photonWeights_RunD.root -> It should be the new one

Alessio

### CODE REVIEW

**Comment by amagitte** [comment]
Ah..
I added a new Met Filter, I commented out the tags for systematic, and in storeTools I switch on the old method.

**Comment by quertenmont** [comment]
**### IMPORTANT ###**
OK.  I made a save of the current master branch (in '7416_16_04_12_74X_Checkpoint' tag)
and I switch the master to this new version which is a prototype for 76X.
If you still want to work in 74X, feel free to populate further the '7416_16_04_12_74X_Checkpoint' branch.

**Comment by vischia** [comment]
Hi @amagitte,

I assume that the target 76X release is CMSSW_7_6_3, could you please
confirm?
The readme still mentions the 7_4_14

Cheers,
Pietro

2016-04-12 9:07 GMT+01:00 Alessio <notifications@github.com>:

> Ah..
> I added a new Met Filter, I commented out the tags for systematic, and in
> storeTools I switch on the old method.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/142#issuecomment-208771283>
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by vischia** [comment]
Hi @amagitte,

another question, sorry: I see that you uploaded the new golden json to the
test/hzz2l2v directory: is this because it is a private json for the
analysis?

If this is the standard json to be used by everyone, it should better go in
the data/json/ directory, in which case I can move it and make a pull
request. Could you please confirm?

Thanks!

Cheers,
Pietro


2016-04-12 9:45 GMT+01:00 Pietro Vischia <pietro.vischia@gmail.com>:

> Hi @amagitte,
>
> I assume that the target 76X release is CMSSW_7_6_3, could you please
> confirm?
> The readme still mentions the 7_4_14
>
> Cheers,
> Pietro
>
> 2016-04-12 9:07 GMT+01:00 Alessio <notifications@github.com>:
>
>> Ah..
>> I added a new Met Filter, I commented out the tags for systematic, and in
>> storeTools I switch on the old method.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms2l2v/2l2v_fwk/pull/142#issuecomment-208771283>
>>
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
I'd be happy with a central json file, indeed.

Loic

2016-04-12 11:14 GMT+02:00 Pietro Vischia <notifications@github.com>:

> Hi @amagitte,
>
> another question, sorry: I see that you uploaded the new golden json to the
> test/hzz2l2v directory: is this because it is a private json for the
> analysis?
>
> If this is the standard json to be used by everyone, it should better go in
> the data/json/ directory, in which case I can move it and make a pull
> request. Could you please confirm?
>
> Thanks!
>
> Cheers,
> Pietro
>
>
> 2016-04-12 9:45 GMT+01:00 Pietro Vischia <pietro.vischia@gmail.com>:
>
> > Hi @amagitte,
> >
> > I assume that the target 76X release is CMSSW_7_6_3, could you please
> > confirm?
> > The readme still mentions the 7_4_14
> >
> > Cheers,
> > Pietro
> >
> > 2016-04-12 9:07 GMT+01:00 Alessio <notifications@github.com>:
> >
> >> Ah..
> >> I added a new Met Filter, I commented out the tags for systematic, and
> in
> >> storeTools I switch on the old method.
> >>
> >> —
> >> You are receiving this because you are subscribed to this thread.
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/142#issuecomment-208771283>
> >>
> >
> >
> >
> > --
> > Pietro Vischia
> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> > Portugal
> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> > office: 00351 21 799 5017
> > mail: pietro.vischia@gmail.com
> > skype: rambling_hadron
> >
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/142#issuecomment-208808824>
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Pull request merged**
