### PR TITLE
updated electron trigger efficiencies for 2016

### PR DESCRIPTION
**Pull request by skeshri**
I have updated electron trigger efficiencies for 2016 Analysis.
Please have a look!

### CODE REVIEW

**Comment by hdelanno** [comment]
Hi Sumit,

Thanks for the PR.
Some small comments:
 - it's a bit weird to have a header file without a .cc one. I know it was already the case before your changes but first time I notice this. I guess we can let it like that, I don't know what others think
 - could you re-indent it quickly? To make it a bit more readible. I'm thinking of the is2016 condition that is at the same level than rest.
 - I guess after this PR you will have a look at this ? https://github.com/cms2l2v/2l2v_fwk/blob/master/bin/hzz2l2v/runHZZ2l2vAnalysis.cc#L1293 
 - in some really rare cases, an electron can have a pseudo-rapidity slightly higher than 2.5 . In this case you apply (1;0) where it would be more physical to propagate the value of the last bin I guess. To me you could rewrite this https://github.com/cms2l2v/2l2v_fwk/pull/208/files#diff-bf24cb0490efefa67fe851841c6eecdbR813 with just a "else"
 - could you add a comment with a hyperlink explaining where those values come from? Or to a talk you made?

NB: I like your second commit :)

**Comment by skeshri** [comment]
Hi Hugues!

I have made changes as you suggested.
But there is some problem with indentation here. 
Please include these changes for now. I will take care of this indentation later.

Also I will change runHZZ2l2vAnalysis now.
Thanks for the suggestions.

**Comment by skeshri** [comment]
Sorry It was for Hugo. ;)

**Comment by hdelanno** [comment]
Hi Sumit,

Thanks for the changes.
What I meant with the pseudo-rapidity > 2.5 is not that. I guess I was not clear.
I meant that all the
 -  else if(eta<2.5) conditions 
should be changed by a
 - else condition
Both for etaCen and etaFwd.
If still not clear I can explain it at the 2l2nu meeting this afternoon.

Ok for the indentation. Just don't forget or at then end the code will look messier and messier.

**Comment by HuguesBrun** [comment]
Hi @hdelanno,
I am surprised that an electron can have an |eta|>2.5 as for an electron eta means the SCeta on which a 2.5 cut is applied in our code (see [here](https://github.com/cms2l2v/2l2v_fwk/blob/master/bin/hzz2l2v/runHZZ2l2vAnalysis.cc#L1071) ).
In general it is the recommandation to compute the efficiencies related to electron versus the SCeta as it is the variable that will reflect the ECAL geometry. 
As SCeta>2.5 should never happen, I am wondering what is the best thing to do technically in the code (use assert to make the code to crash in this case ? )  
@skeshri , you confirm that your SF are computed respect to SCeta, right ?

**Comment by HuguesBrun** [comment]
Ok in fact, after a deeper look at the code I have to correct myself:
- the acceptance cut is indeed applied on SCeta
- but the function getTriggerEfficiencySF use eta in input
So indeed in this case eta can be larger than 2.5 but the call to this function should be fixed to use SCeta

**Comment by skeshri** [comment]
Hi Hugues,

I have calculated Trigger Efficiency wrt SCeta. So all these numbers are with respet to SCeta of two offline electrons. You are right!

**Comment by skeshri** [comment]
I'm closing this pull request and will make a single PR with full changes.

**Pull request closed without merging**
