### PR TITLE
Addition of 2016 data (Run2016B)

### PR DESCRIPTION
**Pull request by hdelanno**
* Addition of the golden json for 2016 ( https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2016Analysis#DATA )
   * after comparison with the triggers in those runs, addition of HLT_Ele22_eta2p1_WPLoose_Gsf_v* to replace HLT_Ele22_eta2p1_WP75_Gsf_v*

### CODE REVIEW

**Comment by georgia14** [comment]
Hi @hdelanno 
Thanks for these updates  . I would think that we need the 2015 and 2016 data samples as separate processes in samples.json (in case of different SFs to come etc ) . Could you please make this small update? Thanks, Georgia

**Comment by hdelanno** [comment]
Hi @georgia14 ,
I don't know exactly about those scale factors, but couldn't we apply them looking at the dtag instead of the tag in the json file ?
It makes more sense for me to have a single object called data than to split the data, especially if we plan to stack 2015 and 2016 data.

Tell me what you think.
Best,
Hugo

**Comment by quertenmont** [comment]
We can and that's what we should do.

However, before merging, I'd like to make sure that you test to run with this PR.
Because how I see it now, it implies you run everything in the same release.
which can't be done from my current understanding

**Comment by georgia14** [comment]
I think that for the moment we want to keep the the two sets of data separately in samples.json , since for example we will not apply any SFs to the 2016B data yet, and/or the releases might need to be changed as you say. So I find many issues to keep separate processes atm before we understand everything :-)

**Comment by quertenmont** [comment]
Splitting the datasets also introduce another bunch of problem.
But let see how it goes first

**Comment by hdelanno** [comment]
Dear all,
With the latest commits to this PR, it now:
 - compiles
 - runs
 - and give meaningful plots.

To achieve this, i've created two new booleans in the main runHZZ2l2vAnalysis.cc
One for 2015 data and one for 2016.
Then I only applied all the 2015 corrections to 2015 data and applied no corrections to 2016. So what is produced for the moment is really raw data for 2016.

I kept one tag for both data (the data tag).
If one wants to run only on 2015 data, one can do "sh submit.sh 1 -t 2015", and accordingly for 2016. Or it can be really easy to edit the samples.json file to test.

If I understood well, the final goal is to have a single "name" in the json with different corrections in the code. Hence the way I wrote it. If you have suggestion, found errors, want things... tell me. This PR is probably not yet ready to be merged in your opinions, but at least we have something to discuss now!

In the process I also added the 2 fb^-1 golden json of today (Friday 10th of June) and also notice some outdated value for the b-tagging (I opened an issue about that).

Cheers,

Hugo

**Comment by vischia** [comment]
Hi @hdelanno ,

can you please confirm that in order to run on the 2016 data the only necessary thing is to use a CMSSW_8_0_X release (any specific subrelease version?), and that the 2015 data must be run in 763p2?

Thanks in advance!

Cheers,
Pietro

**Comment by hdelanno** [comment]
Hi @vischia ,
This preliminary PR is made for 76X, and also to discuss easily how to implement this. It's far from final.

The final goal is to:
STEP 1 - 2016 data and MC:
 - generate the first steps of the analysis on 80X for 2016 data and all the available 80X MC
 - generate the missing 80X MC. This will be done with the 76X MC on the 76X release
 - then copy those 76X MC to 80X release and make the plotter.root
STEP 2:
 - generate the 2015 data and MC on 76X
STEP 3:
 - copy both the plotter.root's for 2015 and 2016 in 76X and "play with them" (to compute the limits, maybe adding them to have something cosmetic and pretty to show, even if it doesn't make a lot of sense)

As you can understand, there is still a lot to do:
1) Going to 8XY (I'm working on this)
2) Looking at this PR, we will also need to add new corrections for 2016
3) writing/editing the scripts to combine 2015 and 2016 for the limits computation.


However, if you want to have a very raw look at 2016 data without 80X MC, then this is what this PR does.


I let @quertenmont add things/correct me :)

Cheers,

Hugo

**Pull request merged**
