### PR TITLE
Merge runPhoJetAnalysis into runHZZ2l2vAnalysis 

### PR DESCRIPTION
**Pull request by xshi**
Hello, 

This will merge the runPhoJetAnalysis with the runHZZ2l2vAnalysis. 

Eventually, we will remove the bin/runPhoJetAnalysis.cc and the hzz2l2v/phojet folder... 

Xin

### CODE REVIEW

**Comment by xshi** [comment]
Hi @georgia14 @quertenmont , could you check if it's okay to merge? 

Thanks!
@xshi

**Comment by quertenmont** [comment]
This is a great move in the right direction to me.
I am happy to bless, but I give some time to @georgia14  to review it too
+1

**Comment by georgia14** [comment]
Hi guys,
Fine with me as well , only minor comment is on the photon_samples.json file: it currently includes the wrong g+jet sample (GJet_Pt-15To6000_TuneCUETP8M1-Flat). You may leave it as is and  will change this with the g-jet in HTbins samples which I have ready, later today . Cheers

**Comment by quertenmont** [comment]
Ok, I merge then!
Thanks

**Pull request merged**
