### PR TITLE
Update for photon sample analysis

### PR DESCRIPTION
**Pull request by xshi**
Because the current runHZZanalysis.cc has commented out the suffix '_filt' for the output file, the runPlotter.cc is also updated accordingly. 

Added 3.1 in submit.sh for photon sample analysis.

### CODE REVIEW

**Comment by quertenmont** [comment]
Hi Xin,

Was there any problem with the _filt suffix in the plotter ?
Commenting this is a bad move to me  for several reasons
1) it can be used by other analyses
2) it will likely be used by us in a near future too
If the use case for this is unclear, it allows to split a sample (ZZ-->4l for instance) into two subsamples which are plotted in different colors in the figures  (ZZ-->4l  vs ZZ-->2l2tau+ZZ-->4taus with l=e or µ)

So I am not sure what is the motivation.

Loic,

PS:  We used it quite a lot to study on-shell vs off-shell higgs production as well

**Comment by xshi** [comment]
Hi Loic, 

Okay, because I don't know the motivation to uncomment the _filt suffix in the main code (runHZZ2l2vAnalysis.cc), I thought it was your intentions to do so.  :) 

If we want to keep it,  I'm happy to restore both codes.  The bottom line is that these two has to be in sync, otherwise, the runPlotter can't process the output files. 

I'll make another commits once my current photon + jets jobs are done.  Then we can merge and close this one. 

Xin

**Comment by xshi** [comment]
Hi @quertenmont , I have changed only the .cc files to accommodate the _filt suffix, please let me know if that's okay. I've tested on some samples, and it works for me. 

Thanks.
Xin

**Comment by quertenmont** [comment]
Sorry, but I still don't believe that this is good.
Can we chat on skype about the problem ?

**Comment by xshi** [comment]
Sure. I'm online.

**Comment by xshi** [comment]
Hi @quertenmont : I've tested and works for me. Hope this version is okay :)

Xin

**Comment by quertenmont** [comment]
Great, thanks Xin (and sorry for all the mess)

**Comment by vischia** [comment]
Hi guys,

if you need a plotter without the _filt suffix you can perhaps use my
bin/chhiggs/runFixedPlotter.cc.

It works by using the old scheme of weighting the events with the cutflow
histogram, though: if you are fine with it, fine. Otherwise, if you want to
use a plotter without "_filt" but with the a-la-Loic computation of the
initial number of events, please copy it and work on a copy (I am not
willing to abandon the cutflow way).

It has a per-histogram support for pseudodata for visualization purposes,
by the way.

Cheers,
Pietro



2015-11-03 16:12 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> Great, thanks Xin (and sorry for all the mess)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/38#issuecomment-153401038>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by xshi** [comment]
Hi Loic, the fix is easier than expected ;) 

Pietro, thanks for pointing us your version. I'll settle with the current version and see if others want to give it a try. 

Xin

**Pull request merged**
