### PR TITLE
cleanup, add PU reweighting

### PR DESCRIPTION
**Pull request by quertenmont**
@vischia Please also update your PU reweighting function to the official Interaction based instead of Vtx based pileup reweighting.  Otherwise the pileup vector  test/runAnalysis_cfg.py.templ will lead to disastrous results.

### CODE REVIEW

**Comment by vischia** [comment]
Hi Loic,

what are you talking about exactly?

I am using the official reweighting recipe based on the pileupcalc official
procedure since when it came out (a couple months ago or so).

Cheers,
Pietro



2015-12-16 15:09 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> @vischia <https://github.com/vischia> Please also update your PU
> reweighting function to the official Interaction based instead of Vtx based
> pileup reweighting. Otherwise the pileup vector
> test/runAnalysis_cfg.py.templ will lead to disastrous results.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cms2l2v/2l2v_fwk/pull/74
> Commit Summary
>
>    - cleanup, add PU reweighting
>
> File Changes
>
>    - *M* bin/common/runPlotter.cc
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-0> (4)
>    - *M* bin/hzz2l2v/runHZZ2l2vAnalysis.cc
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-1> (390)
>    - *M* bin/zhtautau/runZHTauTauAnalysis.cc
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-2> (612)
>    - *M* scripts/runAnalysisOverSamples.py
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-3> (2)
>    - *M* src/MacroUtils.cc
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-4> (2)
>    - *M* test/hzz2l2v/submit.sh
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-5> (9)
>    - *M* test/runAnalysis_cfg.py.templ
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-6> (5)
>    - *M* test/zhtautau/samples.json
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-7> (38)
>    - *M* test/zhtautau/submit.sh
>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-8> (7)
>
> Patch Links:
>
>    - https://github.com/cms2l2v/2l2v_fwk/pull/74.patch
>    - https://github.com/cms2l2v/2l2v_fwk/pull/74.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/74>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by vischia** [comment]
@quertenmont (sorry, I still have to remember to use the github tags for
developers names)

2015-12-16 15:15 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:

> Hi Loic,
>
> what are you talking about exactly?
>
> I am using the official reweighting recipe based on the pileupcalc
> official procedure since when it came out (a couple months ago or so).
>
> Cheers,
> Pietro
>
>
>
> 2015-12-16 15:09 GMT+00:00 Loic Quertenmont <notifications@github.com>:
>
>> @vischia <https://github.com/vischia> Please also update your PU
>> reweighting function to the official Interaction based instead of Vtx based
>> pileup reweighting. Otherwise the pileup vector
>> test/runAnalysis_cfg.py.templ will lead to disastrous results.
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/cms2l2v/2l2v_fwk/pull/74
>> Commit Summary
>>
>>    - cleanup, add PU reweighting
>>
>> File Changes
>>
>>    - *M* bin/common/runPlotter.cc
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-0> (4)
>>    - *M* bin/hzz2l2v/runHZZ2l2vAnalysis.cc
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-1> (390)
>>    - *M* bin/zhtautau/runZHTauTauAnalysis.cc
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-2> (612)
>>    - *M* scripts/runAnalysisOverSamples.py
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-3> (2)
>>    - *M* src/MacroUtils.cc
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-4> (2)
>>    - *M* test/hzz2l2v/submit.sh
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-5> (9)
>>    - *M* test/runAnalysis_cfg.py.templ
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-6> (5)
>>    - *M* test/zhtautau/samples.json
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-7> (38)
>>    - *M* test/zhtautau/submit.sh
>>    <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-8> (7)
>>
>> Patch Links:
>>
>>    - https://github.com/cms2l2v/2l2v_fwk/pull/74.patch
>>    - https://github.com/cms2l2v/2l2v_fwk/pull/74.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms2l2v/2l2v_fwk/pull/74>.
>>
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
No, you do use the function
utils::getMCPileupDistributionFromMiniAODtemp(urls, dataPileupDistribution.
size (), mcPileupDistribution);
Which fills the mcPileupDistribution with the number of reconstructed
vertex.  Instead of filling it with the number of pileup interaction.



2015-12-16 16:16 GMT+01:00 Pietro Vischia <notifications@github.com>:

> @quertenmont (sorry, I still have to remember to use the github tags for
> developers names)
>
>
> 2015-12-16 15:15 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:
>
> > Hi Loic,
> >
> > what are you talking about exactly?
> >
> > I am using the official reweighting recipe based on the pileupcalc
> > official procedure since when it came out (a couple months ago or so).
> >
> > Cheers,
> > Pietro
> >
> >
> >
> > 2015-12-16 15:09 GMT+00:00 Loic Quertenmont <notifications@github.com>:
> >
> >> @vischia <https://github.com/vischia> Please also update your PU
> >> reweighting function to the official Interaction based instead of Vtx
> based
> >> pileup reweighting. Otherwise the pileup vector
> >> test/runAnalysis_cfg.py.templ will lead to disastrous results.
> >> ------------------------------
> >> You can view, comment on, or merge this pull request online at:
> >>
> >> https://github.com/cms2l2v/2l2v_fwk/pull/74
> >> Commit Summary
> >>
> >> - cleanup, add PU reweighting
> >>
> >> File Changes
> >>
> >> - *M* bin/common/runPlotter.cc
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-0> (4)
> >> - *M* bin/hzz2l2v/runHZZ2l2vAnalysis.cc
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-1> (390)
> >> - *M* bin/zhtautau/runZHTauTauAnalysis.cc
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-2> (612)
> >> - *M* scripts/runAnalysisOverSamples.py
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-3> (2)
> >> - *M* src/MacroUtils.cc
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-4> (2)
> >> - *M* test/hzz2l2v/submit.sh
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-5> (9)
> >> - *M* test/runAnalysis_cfg.py.templ
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-6> (5)
> >> - *M* test/zhtautau/samples.json
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-7> (38)
> >> - *M* test/zhtautau/submit.sh
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-8> (7)
> >>
> >> Patch Links:
> >>
> >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.patch
> >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.diff
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/cms2l2v/2l2v_fwk/pull/74>.
> >>
> >
> >
> >
> > --
> > Pietro Vischia
> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> > Portugal
> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> > office: 00351 21 799 5017
> > mail: pietro.vischia@gmail.com
> > skype: rambling_hadron
> >
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165137699>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by vischia** [comment]
Uuuuh nice, that's true!

I was taking event per event the correct number for picking up the scale
factor, but the full distribution for the calculating the scale factors was
still that temp one.

Thanks!
Cheers,
Pietro


2015-12-16 15:20 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> No, you do use the function
> utils::getMCPileupDistributionFromMiniAODtemp(urls, dataPileupDistribution.
> size (), mcPileupDistribution);
> Which fills the mcPileupDistribution with the number of reconstructed
> vertex. Instead of filling it with the number of pileup interaction.
>
>
>
> 2015-12-16 16:16 GMT+01:00 Pietro Vischia <notifications@github.com>:
>
> > @quertenmont (sorry, I still have to remember to use the github tags for
> > developers names)
> >
> >
> > 2015-12-16 15:15 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:
> >
> > > Hi Loic,
> > >
> > > what are you talking about exactly?
> > >
> > > I am using the official reweighting recipe based on the pileupcalc
> > > official procedure since when it came out (a couple months ago or so).
> > >
> > > Cheers,
> > > Pietro
> > >
> > >
> > >
> > > 2015-12-16 15:09 GMT+00:00 Loic Quertenmont <notifications@github.com
> >:
> > >
> > >> @vischia <https://github.com/vischia> Please also update your PU
> > >> reweighting function to the official Interaction based instead of Vtx
> > based
> > >> pileup reweighting. Otherwise the pileup vector
> > >> test/runAnalysis_cfg.py.templ will lead to disastrous results.
> > >> ------------------------------
> > >> You can view, comment on, or merge this pull request online at:
> > >>
> > >> https://github.com/cms2l2v/2l2v_fwk/pull/74
> > >> Commit Summary
> > >>
> > >> - cleanup, add PU reweighting
> > >>
> > >> File Changes
> > >>
> > >> - *M* bin/common/runPlotter.cc
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-0> (4)
> > >> - *M* bin/hzz2l2v/runHZZ2l2vAnalysis.cc
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-1> (390)
> > >> - *M* bin/zhtautau/runZHTauTauAnalysis.cc
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-2> (612)
> > >> - *M* scripts/runAnalysisOverSamples.py
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-3> (2)
> > >> - *M* src/MacroUtils.cc
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-4> (2)
> > >> - *M* test/hzz2l2v/submit.sh
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-5> (9)
> > >> - *M* test/runAnalysis_cfg.py.templ
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-6> (5)
> > >> - *M* test/zhtautau/samples.json
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-7> (38)
> > >> - *M* test/zhtautau/submit.sh
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-8> (7)
> > >>
> > >> Patch Links:
> > >>
> > >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.patch
> > >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.diff
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74>.
> > >>
> > >
> > >
> > >
> > > --
> > > Pietro Vischia
> > > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> > > Portugal
> > > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> > > office: 00351 21 799 5017
> > > mail: pietro.vischia@gmail.com
> > > skype: rambling_hadron
> > >
> >
> >
> >
> > --
> > Pietro Vischia
> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> > Portugal
> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> > office: 00351 21 799 5017
> > mail: pietro.vischia@gmail.com
> > skype: rambling_hadron
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165137699>.
> >
>
>
>
> --
> ---------------------------------------------------------
> Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
> experiment
> Office CERN : bldg.40, RB-08
> Phone CERN : +41 2276 71548
> Mobile BE : +32 474 831531
> WWW : http://www.fynu.ucl.ac.be/users/l.quertenmont/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165138908>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by vischia** [comment]
(funnily enough, that "hybrid" approach was practically working reasonably,
lol)

2015-12-16 15:27 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:

> Uuuuh nice, that's true!
>
> I was taking event per event the correct number for picking up the scale
> factor, but the full distribution for the calculating the scale factors was
> still that temp one.
>
> Thanks!
> Cheers,
> Pietro
>
>
> 2015-12-16 15:20 GMT+00:00 Loic Quertenmont <notifications@github.com>:
>
>> No, you do use the function
>> utils::getMCPileupDistributionFromMiniAODtemp(urls,
>> dataPileupDistribution.
>> size (), mcPileupDistribution);
>> Which fills the mcPileupDistribution with the number of reconstructed
>> vertex. Instead of filling it with the number of pileup interaction.
>>
>>
>>
>> 2015-12-16 16:16 GMT+01:00 Pietro Vischia <notifications@github.com>:
>>
>> > @quertenmont (sorry, I still have to remember to use the github tags for
>> > developers names)
>> >
>> >
>> > 2015-12-16 15:15 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:
>> >
>> > > Hi Loic,
>> > >
>> > > what are you talking about exactly?
>> > >
>> > > I am using the official reweighting recipe based on the pileupcalc
>> > > official procedure since when it came out (a couple months ago or so).
>> > >
>> > > Cheers,
>> > > Pietro
>> > >
>> > >
>> > >
>> > > 2015-12-16 15:09 GMT+00:00 Loic Quertenmont <notifications@github.com
>> >:
>> > >
>> > >> @vischia <https://github.com/vischia> Please also update your PU
>> > >> reweighting function to the official Interaction based instead of Vtx
>> > based
>> > >> pileup reweighting. Otherwise the pileup vector
>> > >> test/runAnalysis_cfg.py.templ will lead to disastrous results.
>> > >> ------------------------------
>> > >> You can view, comment on, or merge this pull request online at:
>> > >>
>> > >> https://github.com/cms2l2v/2l2v_fwk/pull/74
>> > >> Commit Summary
>> > >>
>> > >> - cleanup, add PU reweighting
>> > >>
>> > >> File Changes
>> > >>
>> > >> - *M* bin/common/runPlotter.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-0> (4)
>> > >> - *M* bin/hzz2l2v/runHZZ2l2vAnalysis.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-1> (390)
>> > >> - *M* bin/zhtautau/runZHTauTauAnalysis.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-2> (612)
>> > >> - *M* scripts/runAnalysisOverSamples.py
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-3> (2)
>> > >> - *M* src/MacroUtils.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-4> (2)
>> > >> - *M* test/hzz2l2v/submit.sh
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-5> (9)
>> > >> - *M* test/runAnalysis_cfg.py.templ
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-6> (5)
>> > >> - *M* test/zhtautau/samples.json
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-7> (38)
>> > >> - *M* test/zhtautau/submit.sh
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-8> (7)
>> > >>
>> > >> Patch Links:
>> > >>
>> > >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.patch
>> > >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.diff
>> > >>
>> > >> —
>> > >> Reply to this email directly or view it on GitHub
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74>.
>> > >>
>> > >
>> > >
>> > >
>> > > --
>> > > Pietro Vischia
>> > > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
>> > > Portugal
>> > > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
>> > > office: 00351 21 799 5017
>> > > mail: pietro.vischia@gmail.com
>> > > skype: rambling_hadron
>> > >
>> >
>> >
>> >
>> > --
>> > Pietro Vischia
>> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
>> > Portugal
>> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
>> > office: 00351 21 799 5017
>> > mail: pietro.vischia@gmail.com
>> > skype: rambling_hadron
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165137699>.
>> >
>>
>>
>>
>> --
>> ---------------------------------------------------------
>> Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
>> experiment
>> Office CERN : bldg.40, RB-08
>> Phone CERN : +41 2276 71548
>> Mobile BE : +32 474 831531
>> WWW : http://www.fynu.ucl.ac.be/users/l.quertenmont/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165138908>.
>>
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by vischia** [comment]
OK, I understand why the agreement was reasonable: I am actually offline
not using that weight anymore: in my other code I apply the proper pileup
later on

:)

Cheers,
Pietro

2015-12-16 15:27 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:

> Uuuuh nice, that's true!
>
> I was taking event per event the correct number for picking up the scale
> factor, but the full distribution for the calculating the scale factors was
> still that temp one.
>
> Thanks!
> Cheers,
> Pietro
>
>
> 2015-12-16 15:20 GMT+00:00 Loic Quertenmont <notifications@github.com>:
>
>> No, you do use the function
>> utils::getMCPileupDistributionFromMiniAODtemp(urls,
>> dataPileupDistribution.
>> size (), mcPileupDistribution);
>> Which fills the mcPileupDistribution with the number of reconstructed
>> vertex. Instead of filling it with the number of pileup interaction.
>>
>>
>>
>> 2015-12-16 16:16 GMT+01:00 Pietro Vischia <notifications@github.com>:
>>
>> > @quertenmont (sorry, I still have to remember to use the github tags for
>> > developers names)
>> >
>> >
>> > 2015-12-16 15:15 GMT+00:00 Pietro Vischia <pietro.vischia@gmail.com>:
>> >
>> > > Hi Loic,
>> > >
>> > > what are you talking about exactly?
>> > >
>> > > I am using the official reweighting recipe based on the pileupcalc
>> > > official procedure since when it came out (a couple months ago or so).
>> > >
>> > > Cheers,
>> > > Pietro
>> > >
>> > >
>> > >
>> > > 2015-12-16 15:09 GMT+00:00 Loic Quertenmont <notifications@github.com
>> >:
>> > >
>> > >> @vischia <https://github.com/vischia> Please also update your PU
>> > >> reweighting function to the official Interaction based instead of Vtx
>> > based
>> > >> pileup reweighting. Otherwise the pileup vector
>> > >> test/runAnalysis_cfg.py.templ will lead to disastrous results.
>> > >> ------------------------------
>> > >> You can view, comment on, or merge this pull request online at:
>> > >>
>> > >> https://github.com/cms2l2v/2l2v_fwk/pull/74
>> > >> Commit Summary
>> > >>
>> > >> - cleanup, add PU reweighting
>> > >>
>> > >> File Changes
>> > >>
>> > >> - *M* bin/common/runPlotter.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-0> (4)
>> > >> - *M* bin/hzz2l2v/runHZZ2l2vAnalysis.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-1> (390)
>> > >> - *M* bin/zhtautau/runZHTauTauAnalysis.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-2> (612)
>> > >> - *M* scripts/runAnalysisOverSamples.py
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-3> (2)
>> > >> - *M* src/MacroUtils.cc
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-4> (2)
>> > >> - *M* test/hzz2l2v/submit.sh
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-5> (9)
>> > >> - *M* test/runAnalysis_cfg.py.templ
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-6> (5)
>> > >> - *M* test/zhtautau/samples.json
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-7> (38)
>> > >> - *M* test/zhtautau/submit.sh
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74/files#diff-8> (7)
>> > >>
>> > >> Patch Links:
>> > >>
>> > >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.patch
>> > >> - https://github.com/cms2l2v/2l2v_fwk/pull/74.diff
>> > >>
>> > >> —
>> > >> Reply to this email directly or view it on GitHub
>> > >> <https://github.com/cms2l2v/2l2v_fwk/pull/74>.
>> > >>
>> > >
>> > >
>> > >
>> > > --
>> > > Pietro Vischia
>> > > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
>> > > Portugal
>> > > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
>> > > office: 00351 21 799 5017
>> > > mail: pietro.vischia@gmail.com
>> > > skype: rambling_hadron
>> > >
>> >
>> >
>> >
>> > --
>> > Pietro Vischia
>> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
>> > Portugal
>> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
>> > office: 00351 21 799 5017
>> > mail: pietro.vischia@gmail.com
>> > skype: rambling_hadron
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165137699>.
>> >
>>
>>
>>
>> --
>> ---------------------------------------------------------
>> Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
>> experiment
>> Office CERN : bldg.40, RB-08
>> Phone CERN : +41 2276 71548
>> Mobile BE : +32 474 831531
>> WWW : http://www.fynu.ucl.ac.be/users/l.quertenmont/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms2l2v/2l2v_fwk/pull/74#issuecomment-165138908>.
>>
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Pull request merged**
