### PR TITLE
New Label and New Sample

### PR DESCRIPTION
**Pull request by amagitte**
Hi Xin,

As you suggested, here you are the changes that I used to produce the plots that we discussed one hour ago.

Alessio

### CODE REVIEW

**Comment by amagitte** [comment]
Xin Don't approve it..there is an error in the WZ->2l2q ( I have reported the one of ZZ->2l2q) sorry..

I will redo the pull request now

**Comment by amagitte** [comment]
I have changed it. Sorry.

**Comment by xshi** [comment]
Thanks!

**Comment by xshi** [comment]
I'll make the tag after you circulate the slides incase there is anything new need to be added.

**Pull request merged**
