### PR TITLE
fixed lumimask filename

### PR DESCRIPTION
**Pull request by georgia14**

### CODE REVIEW

**Comment by amagitte** [comment]
Hi Georgia and Xin,

I have a question: why are MC samples setted to the old ones and not to the MiniAODv2?
Do you want that I update them or do you have a precise reason to stay with the old version?

Cheers,
Alessio

**Comment by xshi** [comment]
Hi Alessio, 

Thanks for pointing this out. Georgia and I are currently trying to verify the new code, which we need to compare with the old MC samples. As soon as we done that, we're ready to update to v2. 

Best,
Xin

**Comment by georgia14** [comment]
Hi Alessio,
If you find the chance, yes please you could update the photon+jet samples to  miniAODv2.
Thanks!
Georgia

**Comment by amagitte** [comment]
Hi Georgia!

I read the mail only now…sorry. Sure!

Alessio

**Pull request merged**
