### PR TITLE
Added stitching procedure for HT-binned W+Jets and Drell-Yan samples

### PR DESCRIPTION
**Pull request by vischia**
Dear All,

src/PatUtils.cc contains the method to be used, and also the commented snipped you are supposed to put in the analysis executable.

The list of the samples supported is there as well. 

I tested it on my tau fakes software.

Best regards,
Pietro

### CODE REVIEW

**Comment by quertenmont** [comment]
Hi Pietro,

thanks, can you also add how this is used in your analysis ?
add the call to this function
because like this it's not very clear

**Comment by vischia** [comment]
Hi Loic,

done :)

Cheers,
Pietro

2016-02-03 11:34 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> Hi Pietro,
>
> thanks, can you also add how this is used in your analysis ?
> add the call to this function
> because like this it's not very clear
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/101#issuecomment-179178264>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
Just to be sure, this allows to use TOGETHER the inclusive and the Ht Binned W/Z samples, right ?

**Comment by vischia** [comment]
Yep.

2016-02-03 11:45 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> Just to be sure, this allows to use TOGETHER the inclusive and the Ht
> Binned W/Z samples, right ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/101#issuecomment-179181265>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
cool, will be ueful

**Pull request merged**
