### PR TITLE
Updated JEC payloads

### PR DESCRIPTION
**Pull request by vischia**
Affecting common code:
- new payloads for jet energy corrections (up-to-date with POG twiki)

Useful tools:
- added a couple cfg files that use local ntuples. Useful for testing
- updated trigger list with the triggers available in Run2015D data and in miniaodv2 MC (link in chhiggs/runAnalysis.cc shows how to emulate trigger paths not available in MC)

### CODE REVIEW

**Comment by vischia** [comment]
Hi All,

I just added another feature to this pull request: 

- Fixed behaviour with qsub:
       - modified the check for "bjobs" vs "qsub" to be a check for "bjobs" vs "qstat" (the test on commandoutput for qsub lasts an infinite amount of time at Lisbon Tier2, because qsub opens an interactive environment and breaks up the python flow
       - modified the check for the hostname needed for iihe computing centre. The output of "hostname -f ... iihe" is "-1" at Lisbon, which is != 0 and triggers the request for the queue "localgrid@cream02", which does not exist in Lisbon. Modified by putting the condition ">0", that should satisfy everyone. If it does not, please commit a fix that takes into account the Lisbon behaviour of hostname command (I lost another few hours because I launched the submission command and went away, and it was broken because of the reintroduction of the iihe broken hack).

Cheers,
Pietro

**Comment by vischia** [comment]
Useful tool:
- ntuplizer

Feature addition:
- Data.outLFNDirBase is now configurable at runtime

Bugfix:
- Fixed bug in automatic splitting that was preventing the automatic splitting to work when using CRAB

**Comment by quertenmont** [comment]
Hi Pietro:

◦modified the check for "bjobs" vs "qsub" to be a check for "bjobs" vs "qstat"
This unfortunately doesn't work, because some system (Louvain for instance) do have the qstat command, while we don't have the qsub command.  Can you try to find another fix before I merge?

Thanks
Loic

**Comment by vischia** [comment]
Hi Loic,

2015-10-26 12:25 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> Hi Pietro:
>
> ◦modified the check for "bjobs" vs "qsub" to be a check for "bjobs" vs
> "qstat"
> This unfortunately doesn't work, because some system (Louvain for
> instance) do have the qstat command, while we don't have the qsub command.
> Can you try to find another fix before I merge?
>
I just pushed a fix that sets the test command to "qstat" if a specific
directory path unique to Lisbon is present, and to "qsub" in the other
cases.

Is that OK?

By the way, I am curious: is there any reason for having the qstat command
installed on a system in which does not have also the qsub command? It
looks kind of weird, naively...

Cheers,
Pietro




> Thanks
> Loic
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/26#issuecomment-151116767>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
yep... it also looks insane to me... but that's life unfortunately

**Pull request merged**
