### PR TITLE
updated photon samples

### PR DESCRIPTION
**Pull request by georgia14**
No comments .. :)

### CODE REVIEW

**Comment by quertenmont** [comment]
Looks like you both succeeded ;-)

**Comment by xshi** [comment]
Yeah :+1:

**Comment by georgia14** [comment]
yep

**Comment by xshi** [comment]
Hi @georgia14 ,  could you remove the "split" keyword, and also check the x-section of M-10to50 sample, I found the number should be 18610.0: 

https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIIWinter15GS-MCRUN2_71_V1-v2%2FGEN-SIM&instance=prod%2Fglobal

Then do another PR? 

Thanks!
Xin

**Comment by vischia** [comment]
Hi,

concerning the autosplitting: I get 2300 jobs created, between data and MC.

This seems to me a little too much when compared to the likelihood of
having jobs running in a reasonable amount of time on lxbatch.

It also messes up with the 2000 submitted jobs per-user limit we have in
our Tier2.

What would you think about tuning the autosplitting a bit? I am not against
the concept of "optimal autosplitting", but it does not seem optimal to me.

Cheers,
Pietro

2015-10-28 15:58 GMT+00:00 Xin Shi <notifications@github.com>:

> Hi @georgia14 <https://github.com/georgia14> , could you remove the
> "split" keyword, and also check the x-section of M-10to50 sample, I found
> the number should be 18610.0:
>
>
> https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIIWinter15GS-MCRUN2_71_V1-v2%2FGEN-SIM&instance=prod%2Fglobal
>
> Then do another PR?
>
> Thanks!
> Xin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/32#issuecomment-151892033>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
Hi all,

The auto splitting just do X files per Jobs.
The default value for X is 5. So if you run on 10K files you'll get 2K jobs
(by default).

BUT, you can always change the default when running on a particular json.
To do this, just add to the usual long command
"runAnalysisOverSample....."  the argument "--NFile 20", so you'll get only
500jobs.  (but longer jobs and with a possibly higher faillure rate).

Feel free to add to the submit.sh file a particular number that have your
default runAnalysis... command with this additional argument.  That would
actually be appreciated

Loic






2015-10-28 17:05 GMT+01:00 Pietro Vischia <notifications@github.com>:

> Hi,
>
> concerning the autosplitting: I get 2300 jobs created, between data and MC.
>
> This seems to me a little too much when compared to the likelihood of
> having jobs running in a reasonable amount of time on lxbatch.
>
> It also messes up with the 2000 submitted jobs per-user limit we have in
> our Tier2.
>
> What would you think about tuning the autosplitting a bit? I am not against
> the concept of "optimal autosplitting", but it does not seem optimal to me.
>
> Cheers,
> Pietro
>
> 2015-10-28 15:58 GMT+00:00 Xin Shi <notifications@github.com>:
>
> > Hi @georgia14 <https://github.com/georgia14> , could you remove the
> > "split" keyword, and also check the x-section of M-10to50 sample, I found
> > the number should be 18610.0:
> >
> >
> >
> https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIIWinter15GS-MCRUN2_71_V1-v2%2FGEN-SIM&instance=prod%2Fglobal
> >
> > Then do another PR?
> >
> > Thanks!
> > Xin
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cms2l2v/2l2v_fwk/pull/32#issuecomment-151892033>.
> >
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/32#issuecomment-151894211>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Pull request merged**
