### PR TITLE
 	Merge WJets inclusive and HT>100 while avoiding double counting

### PR DESCRIPTION
**Pull request by hdelanno**
This commit merges our old two WJets samples (inclusive and HT>100) into a single one. The main code is taking care of avoiding double counting.
This should improve the photon control region but also the Instr. MET.

By doing this, I also notice that the samples_full2016.json file does not contain the parts playing with mixing (like the construction of the genuine MET and Instr. MET). I guess it is meant and so I didn't touch this part (adding the Instr. MET etc).
Furthermore, this sample cannot be launched for me and it throws an error, so I could only test it on samples_Spring16_full2016.json

Please also note that the script of Hugues may need to be update to take care of this new definition of the WJets sample.

### CODE REVIEW

**Comment by georgia14** [comment]
Hi @hdelanno 

Do I understand well that the main json file (samples_full2016.json ) by Hugues does not contain the mixing part where the instr. MET is build . This is a very serious missing part . 

Could you please update it to excatly how it used to be ?

Many thanks for noticing this!

ps : I am bit hesitant to merge anything into the main code before preapproval . We are currently running the analysis and it is not very safe to change the code few days before preapproval .

Please could you update the PR for samples_full2016.json ?

Many thanks
Georgia

**Comment by hdelanno** [comment]
Hi @georgia14,
This is not super critical so if you don't feel it we can merge it later. I'm running on the W+jets part at the moment so, if you want, you can send me your plotter and I can add the W+jets sample and produce the plots with it.

About the samples_full2016.json, my main issue is if I run the code out-of-the-box I have the following error with this json: "No JSON object could be decoded". Do you also have this issue? Once this is fixed, I can add the "mixing" parts to the json (Instr. MET, genuine... in a nutshell, all the parts that involve mixing of different datasets).

Cheers,

Hugo

**Comment by georgia14** [comment]
Hi @hdelanno 

The crash with samples_full2016.json will hopefully be fixed with a new PR from Alessio now . Its the same for us here.

It would be great if you can then add all the "mix " parts as we used to . Thanks!

As for Wjets , I suggest we merge this after preapproval . You need to validate this also  in the signal region and see how the Wmixing performs there. Then we can merge .

cheers,Georgia

**Comment by georgia14** [comment]
@hdelanno  : ok now samples_full2016.json must be fixed . You can check out the new one .

**Comment by hdelanno** [comment]
Addition of the missing samples (like in #294) with already the correction for the W+jets merging.

**Comment by georgia14** [comment]
Hi @hdelanno 

We need a PR only with the addition of the mixing part . Can you please update ? thanks

**Pull request merged**
