### PR TITLE
Aligning with latest changes, and cleanup of chhiggs code

### PR DESCRIPTION
**Pull request by vischia**

### CODE REVIEW

**Comment by quertenmont** [comment]
sorry for the delay

**Comment by vischia** [comment]
No problem!

:)

Ah Loic, Alex (in CC) is a student from LIP that has started to use our
framework, so I guess that at some point he will start making pull requests
as well :)

Cheers,
Pietro


2015-12-01 9:22 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> sorry for the delay
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/58#issuecomment-160905450>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
OK.

Let me know if I should add him to the developer list or so.

2015-12-01 10:27 GMT+01:00 Pietro Vischia <notifications@github.com>:

> No problem!
>
> :)
>
> Ah Loic, Alex (in CC) is a student from LIP that has started to use our
> framework, so I guess that at some point he will start making pull requests
> as well :)
>
> Cheers,
> Pietro
>
>
> 2015-12-01 9:22 GMT+00:00 Loic Quertenmont <notifications@github.com>:
>
> > sorry for the delay
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cms2l2v/2l2v_fwk/pull/58#issuecomment-160905450>.
> >
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/58#issuecomment-160906802>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by vischia** [comment]
Oh right, now we have the developers list!

I guess it would be nice! His github username is xealits

Cheers,
Pietro



2015-12-01 9:32 GMT+00:00 Loic Quertenmont <notifications@github.com>:

> OK.
>
> Let me know if I should add him to the developer list or so.
>
> 2015-12-01 10:27 GMT+01:00 Pietro Vischia <notifications@github.com>:
>
> > No problem!
> >
> > :)
> >
> > Ah Loic, Alex (in CC) is a student from LIP that has started to use our
> > framework, so I guess that at some point he will start making pull
> requests
> > as well :)
> >
> > Cheers,
> > Pietro
> >
> >
> > 2015-12-01 9:22 GMT+00:00 Loic Quertenmont <notifications@github.com>:
> >
> > > sorry for the delay
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cms2l2v/2l2v_fwk/pull/58#issuecomment-160905450>.
> > >
> >
> >
> >
> > --
> > Pietro Vischia
> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> > Portugal
> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> > office: 00351 21 799 5017
> > mail: pietro.vischia@gmail.com
> > skype: rambling_hadron
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cms2l2v/2l2v_fwk/pull/58#issuecomment-160906802>.
> >
>
>
>
> --
> ---------------------------------------------------------
> Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
> experiment
> Office CERN : bldg.40, RB-08
> Phone CERN : +41 2276 71548
> Mobile BE : +32 474 831531
> WWW : http://www.fynu.ucl.ac.be/users/l.quertenmont/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/pull/58#issuecomment-160908290>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Pull request merged**
